version: 1.0.0
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root